### ISSUE TITLE
Support tags in Config

### ISSUE THREAD

**Issue by jespersm** [mmitteregger/cuke-runner#5]
As in the example, the `Config`struct has a field called `tags`which is currently a no-op. Was this intended to be compiled into a TagPredicate internally to filter the scenarios and tests to run?

```
    let config = Config {
        features_dir: &[env!("CARGO_MANIFEST_DIR"), "tests", "features"].iter().collect::<PathBuf>(),
        output_dir: &[env!("CARGO_MANIFEST_DIR"), "target", "cucumber"].iter().collect::<PathBuf>(),
        strict: true,
        colored_output: true,
        dry_run: false,
        tags: vec![],
        execution_mode: ExecutionMode::Sequential {
            event_listeners: &[
                &PrettyFormatter::new(),
            ],
        },
    };
```

You you accept a PR for such a feature?

**Comment by mmitteregger** [comment]
Hi, sorry for the late response again.

I have updated the code to support tags a long time ago in the `next` branch (see c237ad171270f9290e440fe4f7f1c3238470e09c) but did not merge it back into the master branch. That should be fixed now, I have pushed all my changes into the master branch.

There are some breaking changes though. Please look at the [calculator example](https://github.com/mmitteregger/cuke-runner/tree/master/examples/calculator) for details.

New config:
```rust
let config = Config {
    features_dir: &[env!("CARGO_MANIFEST_DIR"), "tests", "features"].iter().collect::<PathBuf>(),
    output_dir: &[env!("CARGO_MANIFEST_DIR"), "target", "cucumber"].iter().collect::<PathBuf>(),
    strict: true,
    colored_output: true,
    dry_run: false,
    tags: &["not @ignore"],
    execution_mode: ExecutionMode::Sequential {
        event_listeners: &[
            &PrettyPrintListener::new(),
        ],
    },
};
```

Steps now need the `#[scenario]` parameter attribute:
```rust
#[given("a calculator I just turned on")]
pub fn reset_calculator(#[scenario] calc: &mut Calc) {
    calc.reset();
}
```

On the plus side the code now finally works with the latest stable compiler `1.46.0`.
